"""Step 3 — structured summarization pipeline (see step-3-summarization.md).

Turns a Step 2 merged transcript into a structured meeting summary — agenda
items + outcome, decisions, action items, and goal status — generated by a
local LLM enriched with live app/MongoDB context (goals, activity logs,
discussion points). Completing this step gives a shippable v1 of the whole
feature: record → transcribe → merge → summarize.

Fully local: no API calls, no server-side processing (same constraint as
meeting_recorder.py / meeting_transcriber.py). Two backends, tried in this
order:
  1. An already-running local Ollama instance (http://localhost:11434) —
     detected with a short `requests` probe (`requests` is already a project
     dependency; see notifications.py / app_update.py). Used if present so
     people who already run Ollama don't pay for a second copy of the model
     on disk.
  2. An embedded llama.cpp instance via llama-cpp-python (pip package,
     embeds llama.cpp in-process — no separate server binary to manage,
     fits an already pip-based requirements.txt), against a local GGUF
     model file. There's no auto-download for this file (unlike
     meeting_transcriber.py's faster-whisper hub download) since GGUF
     quant/licence choice is something to be intentional about; see
     get_embedded_model_path for where the file is expected.

Model: Llama 3.1 8B Instruct or Qwen2.5 7B Instruct, Q4_K_M quantization —
realistic on CPU-only consumer hardware, not real-time but fine for a
post-meeting batch job (matches meeting_transcriber.py's faster-whisper
"small" choice for the same hardware target).

Threading model matches meeting_transcriber.py: summarize_meeting() below is
a plain (blocking, CPU-heavy) function; SummarizationJob runs it on its own
daemon thread the same way TranscriptionJob/MeetingRecorder do, and callers
marshal on_status/on_error/on_done back to the Tk main loop themselves via
self.after(0, ...) — the same pattern meeting.py already uses for both.

Note for Step 6 (meeting_reconciler.py): this module's two low-level backend
call points, _generate_ollama and _generate_embedded, are imported from here
rather than duplicated, since they *are* the local-LLM call rather than a
tiny module-local helper (contrast _notify/_atomic_write, which each module
keeps its own copy of). summarize_meeting() also accepts an optional
transcript_override_path so callers can point it at reconciled.md instead of
merged.md once Step 6 has produced one for a meeting.
"""
from __future__ import annotations

import json
import os
import threading
import time
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import requests

from meeting_recorder_paths import get_models_dir, merged_transcript_path, meta_path, summary_path
from mongo_doc_lookup import week_bucket_from_agg, week_goals
from period_model import (
    as_utc,
    monday_midnight_local,
    period_keys,
    to_local,
    utc_naive_after_calendar_days,
)
from timetable_db import aggregations, collection, status_meeting

OLLAMA_BASE_URL = "http://localhost:11434"
_OLLAMA_PROBE_TIMEOUT_SECONDS = 1.0
_OLLAMA_GENERATE_TIMEOUT_SECONDS = 600.0

# Any of these dropped into the app's data dir under models/ is used as-is,
# first match wins — see get_embedded_model_path.
_EMBEDDED_MODEL_FILENAME_CANDIDATES = (
    "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
    "Qwen2.5-7B-Instruct-Q4_K_M.gguf",
)
# Public alias - meeting_recorder_setup.py needs these same filenames to know
# what to download and where to check whether setup has already completed.
EMBEDDED_MODEL_FILENAME_CANDIDATES = _EMBEDDED_MODEL_FILENAME_CANDIDATES
_EMBEDDED_MODEL_ENV_VAR = "ELG_SUMMARIZER_MODEL_PATH"
_EMBEDDED_N_CTX = 8192
_EMBEDDED_MAX_TOKENS = 2000


class SummarizerConfigError(Exception):
    """Neither a reachable Ollama instance nor a local GGUF model file was found."""


@dataclass(frozen=True)
class SummarizationResult:
    summary_path: Path
    backend: str  # "ollama" or "embedded"
    model_name: str
    processing_seconds: float


def _notify(on_progress: Callable[[str], None] | None, message: str) -> None:
    if on_progress is None:
        return
    try:
        on_progress(message)
    except Exception:
        pass


# --- backend discovery ---

def _ollama_running_model() -> str | None:
    """Name of the first locally-pulled Ollama model, or None if Ollama isn't reachable."""
    try:
        response = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=_OLLAMA_PROBE_TIMEOUT_SECONDS)
        response.raise_for_status()
    except requests.exceptions.RequestException:
        return None
    models = response.json().get("models") or []
    if not models:
        return None
    return models[0].get("name")


def get_embedded_model_path() -> Path:
    """Resolve a local GGUF model file: env var override, else models/ next to meetings/
    in the app's per-user data dir (same platformdirs root storage.py/meeting_recorder_paths.py use)."""
    env_path = os.environ.get(_EMBEDDED_MODEL_ENV_VAR)
    if env_path:
        path = Path(env_path)
        if path.is_file():
            return path
        raise SummarizerConfigError(
            f"{_EMBEDDED_MODEL_ENV_VAR} is set to '{env_path}', but no file exists there."
        )

    models_dir = get_models_dir()
    for filename in _EMBEDDED_MODEL_FILENAME_CANDIDATES:
        candidate = models_dir / filename
        if candidate.is_file():
            return candidate

    raise SummarizerConfigError(
        "No local LLM available for meeting summarization. Either run Ollama with a "
        "model pulled, or place one of "
        f"{', '.join(_EMBEDDED_MODEL_FILENAME_CANDIDATES)} in "
        f"'{models_dir}' (or point {_EMBEDDED_MODEL_ENV_VAR} at a GGUF file)."
    )


# --- MongoDB app context (see meeting.py's equivalents for the same queries
# against live per-user/session state; these are the week-scoped shape of
# the same data, since this module has no live week-anchor of its own) ---

def _week_bounds(meeting_start_utc: datetime) -> tuple[datetime, datetime]:
    """UTC-naive [week_start, week_end) for the Monday-Sunday local week
    containing meeting_start_utc — mirrors meeting.py's WEEK_PIPELINE-derived
    current_week_start/next_week_start, computed directly since this module
    doesn't have meeting.py's live "State" doc anchor."""
    week_start = as_utc(monday_midnight_local(meeting_start_utc)).replace(tzinfo=None)
    week_end = utc_naive_after_calendar_days(week_start, 7)
    return week_start, week_end


def _fetch_goal_status(iso_year: str, iso_week: str) -> list[dict]:
    """Every user's goal vs. actual progress for the week — same underlying
    data as notifications.py's fetch_week_goal_context (Goals doc + the
    matching aggregation bucket), but for every user who set a goal that
    week rather than one user at a time."""
    goals_doc = status_meeting.find_one({"_id": "Goals"}) or {}
    week_goal_map = week_goals(goals_doc, iso_year, iso_week)

    results = []
    for username, user_goals in week_goal_map.items():
        agg = aggregations.find_one({"_id": username}) or {}
        bucket = week_bucket_from_agg(agg, iso_year, iso_week)
        goal_hours = int(user_goals.get("hours") or 0)
        goal_days = int(user_goals.get("days") or 0)
        actual_hours = round(int(bucket.get("time") or 0) / 3600, 1)
        actual_days = int(bucket.get("active_days") or 0)
        results.append({
            "user": username,
            "goal_hours": goal_hours,
            "actual_hours": actual_hours,
            "hours_reached": goal_hours == 0 or actual_hours >= goal_hours,
            "goal_days": goal_days,
            "actual_days": actual_days,
            "days_reached": goal_days == 0 or actual_days >= goal_days,
        })
    results.sort(key=lambda entry: entry["user"])
    return results


def _fetch_activity_logs(week_start: datetime, week_end: datetime) -> list[dict]:
    """Timetable entries for the week — same query shape as meeting.py's _fetch_logs."""
    logs = list(collection.find({"timestamp": {"$gte": week_start, "$lt": week_end}}))
    logs.sort(key=lambda log: log.get("timestamp") or datetime.min)
    return logs


def _fetch_discussion_points(iso_year: str, iso_week: str) -> list[dict]:
    """Meeting agenda for the week — same query shape as meeting.py's _fetch_discussion_points."""
    doc = status_meeting.find_one(
        {"_id": "Discussion Points"},
        projection={f"{iso_year}.{iso_week}": 1},
    ) or {}
    return doc.get(iso_year, {}).get(iso_week, [])


# --- prompt construction ---

def _format_goal_status_block(goal_status: list[dict]) -> str:
    if not goal_status:
        return "No goals were set for this week."
    lines = []
    for entry in goal_status:
        hours_state = "reached" if entry["hours_reached"] else "not reached"
        days_state = "reached" if entry["days_reached"] else "not reached"
        lines.append(
            f"- {entry['user']}: {entry['actual_hours']:g}h logged vs. {entry['goal_hours']}h goal "
            f"(hours goal {hours_state}); {entry['actual_days']} vs. {entry['goal_days']} active-days goal "
            f"(days goal {days_state})"
        )
    return "\n".join(lines)


def _format_activity_logs_block(logs: list[dict]) -> str:
    if not logs:
        return "No activity was logged this week."
    lines = []
    for log in logs:
        user = log.get("user", "?")
        name = log.get("name") or "Untitled session"
        elapsed = int(log.get("elapsed_time") or 0)
        ts = log.get("timestamp")
        when = to_local(ts).strftime("%a %H:%M") if ts else "?"
        lines.append(f"- {user} — {name} ({when}, {elapsed // 3600}h{(elapsed % 3600) // 60:02d}m)")
    return "\n".join(lines)


def _format_discussion_points_block(points: list[dict]) -> str:
    if not points:
        return "No agenda was set ahead of this meeting."
    lines = []
    for point in points:
        title = point.get("title", "")
        description = point.get("description")
        lines.append(f"- {title}" + (f": {description}" if description else ""))
    return "\n".join(lines)


def _build_prompt(
    transcript: str,
    goal_status: list[dict],
    activity_logs: list[dict],
    discussion_points: list[dict],
) -> str:
    return f"""You are an assistant summarizing a weekly status meeting for a small indie game studio, from a speaker-labeled transcript plus live app data.

## Meeting agenda (Discussion Points set ahead of the meeting)
{_format_discussion_points_block(discussion_points)}

## This week's goal status (from the app's tracked hours/activity)
{_format_goal_status_block(goal_status)}

## This week's logged activity
{_format_activity_logs_block(activity_logs)}

## Transcript
{transcript}

---
Write a structured Markdown meeting summary with exactly these sections, in this order:

## Agenda Items
For each agenda item listed above (and any other major topic actually
discussed), a short heading and 1-3 sentences on what was said and how it
was resolved. If an agenda item was not actually discussed, say so briefly.

## Decisions
A bullet list of concrete decisions made. If none, say "No decisions were recorded."

## Action Items
A bullet list formatted as `- [Owner] Task` — infer the owner from who
volunteered or was assigned in the transcript. If none, say "No action
items were recorded."

## Goal Status
For each person in the goal status data above, one line explicitly stating
whether their hours goal and days goal were reached, referencing the actual
numbers. If the transcript discusses *why* a goal was or wasn't reached,
fold that reasoning in.

Ground everything in the transcript and the app data above — don't invent
names, numbers, or decisions that aren't supported by them."""


# --- backends ---

def _generate_ollama(prompt: str, model_name: str) -> str:
    response = requests.post(
        f"{OLLAMA_BASE_URL}/api/generate",
        json={"model": model_name, "prompt": prompt, "stream": False},
        timeout=_OLLAMA_GENERATE_TIMEOUT_SECONDS,
    )
    response.raise_for_status()
    return response.json()["response"].strip()


def _generate_embedded(prompt: str, model_path: Path) -> str:
    from llama_cpp import Llama  # imported lazily — heavy native extension, only needed here

    llm = Llama(model_path=str(model_path), n_ctx=_EMBEDDED_N_CTX, verbose=False)
    result = llm.create_chat_completion(
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=_EMBEDDED_MAX_TOKENS,
    )
    return result["choices"][0]["message"]["content"].strip()


# --- meta/output helpers (mirrors meeting_transcriber.py's equivalents) ---

def _load_meeting_meta(meeting_start_utc: datetime) -> dict:
    path = meta_path(meeting_start_utc)
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def _atomic_write(path: Path, content: str) -> None:
    """tmp + os.replace, matching meeting_recorder_paths.write_meeting_meta's pattern."""
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    with open(tmp_path, "w", encoding="utf-8") as file:
        file.write(content)
        file.flush()
        os.fsync(file.fileno())
    os.replace(tmp_path, path)


def _format_header(meeting_start_utc: datetime, meta: dict, backend: str, model_name: str) -> str:
    lines = ["# Meeting Summary", "", f"- Start (UTC): {meeting_start_utc.isoformat()}"]
    participants = meta.get("participants") or {}
    participant_names = sorted(
        entry.get("display_name") or entry.get("username") or user_id
        for user_id, entry in participants.items()
    )
    if participant_names:
        lines.append(f"- Participants: {', '.join(participant_names)}")
    lines.append(f"- Generated by: {model_name} ({backend})")
    lines.extend(["", "---", ""])
    return "\n".join(lines)


def summarize_meeting(
    meeting_start_utc: datetime,
    *,
    on_progress: Callable[[str], None] | None = None,
    transcript_override_path: Path | None = None,
) -> SummarizationResult:
    """Turn a transcript into a structured summaries/summary.md.

    By default reads Step 2's merged_transcript_path() (speaker-labeled,
    chronological). Pass transcript_override_path to point this at a
    different transcript instead — e.g. Step 6's reconciled_transcript_path()
    once that's available for a meeting — without otherwise changing this
    function's shape (still blocking, still just an on_progress callback).
    Any plain-text transcript works here; this function doesn't care which
    step produced it.

    Blocking / CPU-heavy — see module docstring for the expected threading
    model. Raises RuntimeError if the resolved transcript path doesn't exist
    (e.g. Step 2 wasn't run for this meeting), and SummarizerConfigError if
    neither backend is available.
    """
    transcript_path = transcript_override_path or merged_transcript_path(meeting_start_utc)
    if not transcript_path.exists():
        raise RuntimeError(
            f"No transcript found at {transcript_path} — was this meeting transcribed (Step 2)?"
        )
    transcript = transcript_path.read_text(encoding="utf-8")

    _notify(on_progress, "Gathering app context…")
    keys = period_keys(meeting_start_utc)
    week_start, week_end = _week_bounds(meeting_start_utc)
    goal_status = _fetch_goal_status(keys.iso_week_year, keys.iso_week)
    activity_logs = _fetch_activity_logs(week_start, week_end)
    discussion_points = _fetch_discussion_points(keys.iso_week_year, keys.iso_week)

    prompt = _build_prompt(transcript, goal_status, activity_logs, discussion_points)

    ollama_model = _ollama_running_model()
    start_perf = time.perf_counter()
    if ollama_model:
        _notify(on_progress, f"Summarizing with local Ollama ({ollama_model})…")
        body = _generate_ollama(prompt, ollama_model)
        backend, model_name = "ollama", ollama_model
    else:
        model_path = get_embedded_model_path()
        _notify(on_progress, f"Loading embedded model ({model_path.name})…")
        body = _generate_embedded(prompt, model_path)
        backend, model_name = "embedded", model_path.name
    processing_seconds = time.perf_counter() - start_perf

    meta = _load_meeting_meta(meeting_start_utc)
    header = _format_header(meeting_start_utc, meta, backend, model_name)
    out_path = summary_path(meeting_start_utc)
    _atomic_write(out_path, header + "\n" + body + "\n")

    _notify(on_progress, "Summarization complete.")

    return SummarizationResult(
        summary_path=out_path,
        backend=backend,
        model_name=model_name,
        processing_seconds=processing_seconds,
    )


class SummarizationJob:
    """Runs summarize_meeting() on its own daemon thread.

    Mirrors meeting_transcriber.py's TranscriptionJob: a dedicated
    background thread owns the work; this class does not marshal callbacks
    back to Tk itself — callers (see meeting.py) wrap
    on_status/on_error/on_done with self.after(0, ...) themselves.
    """

    def __init__(self) -> None:
        self._thread: threading.Thread | None = None
        self._running = threading.Event()

    @property
    def is_running(self) -> bool:
        return self._running.is_set()

    def start(
        self,
        meeting_start_utc: datetime,
        *,
        on_status: Callable[[str], None],
        on_error: Callable[[Exception], None],
        on_done: Callable[[SummarizationResult], None],
    ) -> None:
        if self._running.is_set():
            return
        self._running.set()
        self._thread = threading.Thread(
            target=self._run,
            name="meeting_summarizer",
            daemon=True,
            args=(meeting_start_utc, on_status, on_error, on_done),
        )
        self._thread.start()

    def _run(
        self,
        meeting_start_utc: datetime,
        on_status: Callable[[str], None],
        on_error: Callable[[Exception], None],
        on_done: Callable[[SummarizationResult], None],
    ) -> None:
        try:
            result = summarize_meeting(meeting_start_utc, on_progress=on_status)
        except Exception as exc:  # noqa: BLE001 - surfaced to the caller via on_error
            self._safe_call(on_error, exc)
        else:
            self._safe_call(on_done, result)
        finally:
            self._running.clear()

    @staticmethod
    def _safe_call(fn: Callable | None, *args: Any) -> None:
        if fn is None:
            return
        try:
            fn(*args)
        except Exception:
            pass
