"""Shared colors and dimensions for settings UI widgets."""

CARD_BG = "#2B2B2B"
CARD_CORNER = 8
ROW_PADX = 16
ROW_PADY = 10
FONT_TITLE = ("Segoe UI", 28, "bold")
FONT_SECTION = ("Segoe UI", 13, "bold")
FONT_ROW = ("Segoe UI", 13)
FONT_MUTED = ("Segoe UI", 12)
TEXT_MUTED = "#9A9A9A"
SEPARATOR_COLOR = "#3A3A3A"
ACCENT = "#50ffd2"
ACCENT_DIM = "#2a8f74"
SWITCH_ON = ACCENT
SWITCH_OFF_FILL = CARD_BG
SWITCH_BORDER = "#8A8A8A"
SWITCH_THUMB_ON = "#141414"
SWITCH_THUMB_OFF = "#B8B8B8"
SWITCH_TRACK_WIDTH = 44
SWITCH_TRACK_HEIGHT = 22
SWITCH_GAP = 3
SWITCH_BORDER_WIDTH = 1.5
CHEVRON_COLOR = "#C8C8C8"
CHEVRON_SIZE = 28
FIELD_WIDTH = 220
FIELD_FG = "#333333"
FIELD_BORDER = "#444444"
